neverware/gondar

src/gondar.cc, src/gondar.h, src/msapi_utf8.h, src/shared.h, src/stubs.cc
Also replaced `TRUE` with `true` and `FALSE` with `false`.
I left a few instances of non-standard booleans alone so that I don't
accidentally break compatibility with any Windows API functions.
=> Replace BOOL with a standard C++ bool

src/device.cc, src/device.h, src/gondar.cc, src/gondarwizard.cc
Removed the "have a nice day" printfs and the associated
`DeviceGuyList_print` function. The devices are now logged in
`UsbInsertPage::getDriveList`.
=> Replace more debug printfs with logging

src/device.cc, src/device.h, src/gondarwizard.cc
This is a minimal replacement; the same functions as before still
exist, just with simpler implementations. I plan to simplify the rest
separately.
=> Replace DeviceGuyList with a typedef'd vector

src/device.cc, src/device.h, src/diskwritethread.cc
Removed the two free functions and replace with constructors.
=> Clean up DeviceGuy

src/device.cc, src/device.h, src/gondar.cc, src/gondar.h, src/gondarwizard.cc, src/stubs.cc
This removes the init and free functions for DeviceGuyList, and the
main `drivelist` variable is no longer a pointer.
=> Remove the pointerness of the DeviceGuyList

src/device.cc, src/device.h, src/gondarwizard.cc
In an earlier change I misinterpreted the selected index as being an
index into the container, rather than the device_num.
=> Fix device lookup

src/device.cc, src/device.h, src/log.cc, src/log.h, src/usb_insert_page.cc
This just makes logging a device a little more convenient.
=> logger: add support for DeviceGuy type

CMakeLists.txt, src/device.cc, src/device.h, src/device_picker.cc, src/device_picker.h, src/device_select_page.cc, src/device_select_page.h, src/option.h, test/test.cc, test/test.h
I have bundled a number of things into this PR as you requested.
One behavioral difference: the device selection page now disables the Next button until a device is selected.
Also, there is now an actual unit test.
=> Refactor some device picking stuff

.gitmodules, CMakeLists.txt, docker/gondar-win32.Dockerfile, infra/gdisk.cmake, src/gondar.cc, src/gpt_pal.cc, src/gpt_pal.h
=> Use GDisk to clean MBR/GPT before writing

src/chromeover_login_page.cc
=> Prompt user for email instead of username

src/meepo.cc
Addresses OVER-5322
Addresses OVER-5317
=> Now send username/password as part of post data

src/chromeover_login_page.cc, src/chromeover_login_page.h, src/meepo.cc, src/util.cc, src/util.h
=> Added 'forgot password?' link

src/chromeover_login_page.cc
@smithforrestr  has now specified he wants this link always and forever
=> now always show forgot password link

src/about_dialog.cc, src/about_dialog.h, src/gondarimage.h, src/gondarwizard.cc, src/gondarwizard.h, src/metric.cc, src/update_check.cc, src/util.cc, src/util.h
Addresses OVER-5336
Also adds the current version number to the window title
=> Check if there is a newer version, display message

src/meepo.cc, src/update_check.cc, src/util.cc, src/util.h
Addresses OVER-5376
This should work already; just change the current version in util.cc; 1.8 and below should pop up the update
=> Now use a JSON file in prod AWS for gondar update check

gondar-release.py, src/gondar.cc
=> Create release script for Gondar

src/device.cc, src/device.h, src/device_picker.cc, src/gondar.cc, src/stubs.cc, src/util.cc, src/util.h, src/write_operation_page.cc, test/test.cc
=> Gray out disks that are too small

src/image_select_page.cc
Addresses OVER-5415
Also reworks validatePage logic for clarity across versions.
=> Chromeover users must now select an image

gondar-release.py, requirements.txt
I couldn't find a requirements.txt file in here, so I figured we needed one.
=> Dgs3 gondar release imports

gondar-release.py
=> Fixed type

.gitmodules
The remote we used in the past has been X_X for over 24 hours.
=> update gdisk remote

src/device.h, src/gpt_pal.cc, test/test.cc
Slightly reduce the number of changes I'm shoving down the pipe with this upcoming test refactor PR
=> ran clang-format

src/device_select_page.cc, src/download_progress_page.cc, src/usb_insert_page.cc
note that there are some other goodies requested in that ticket like font size change that will take more than 1 second to complete so i haven't done them yet
=> made copy changes requested in OVER-5347

resources/style.css, src/main.cc
This may end up being too big.  Now that we have a means of changing it and we don't like the default, it will be easy to toy around with the constant.
=> embiggen font for OVER-5347

src/download_progress_page.cc, src/downloader.cc, src/downloader.h, src/metric.cc, src/metric.h
=> Now handle network failures and send metric

resources/style.css, src/device_picker.cc, src/device_select_page.cc, src/device_select_page.h, src/download_progress_page.cc, src/write_operation_page.cc, src/write_operation_page.h
addresses OVER-5495
I will also likely need to either shrink the font size or increase the starting window size.  I haven't tested on winders yet.
=> add What is next? section to final screen

src/admin_check_page.cc
I just noticed we never close this paragraph when I was in the neighborhood.  Qt doesn't seem to mind, but I submit this for the approval of the midnight society.
=> close paragraph in label

src/write_operation_page.cc
Addresses OVER-5567
I have yet to test this on a winders machine.
=> Fix "what's next" prompt for 'make another usb' case

src/metric.cc, src/metric.h, src/site_select_page.cc
Addresses OVER-5622
Feel free to suggest an alternative to my static member method for storing state in the metrics layer.
=> Include site id in metrics when available

CMakeLists.txt, src/chromeover_login_page.cc, src/dismissprompt.cc, src/dismissprompt.h, src/gondar.cc, src/main.cc, src/metric.cc, src/msapi_utf8.h, src/shared.h
TODO: work for different (non-english) locales
Addresses OVER-6235
I still have some cleaning up to do but YGtI
=> Use code from current version of rufus to dismiss windows format popups

src/metric.cc, src/metric.h, src/write_operation_page.cc
Add new metrics for formatting USBs
=> Kendall warp tunnel 13 with metric

src/write_operation_page.cc
Addresses OVER-7504
Ok so maybe just one more difference between the two cases.
=> Use separate text for format operation

src/hdd_vs_ufd.h, src/image_select_page.cc, src/image_select_page.h
=> Add confirmation popup for 32-bit image selection

codebuild/buildlinux.yml, codebuild/buildwin.yml, codebuild/runlinux.yml, codebuild/runwin.yml, docker/gondar-linux.Dockerfile
Addresses OVER-7527 and OVER-7531
=> Changes to allow codebuild to create and run dockerfiles

src/image_select_page.cc
@hiyeran noticed I only fixed this for beerover.
=> Kendall 32 warn chromeover

src/write_operation_page.cc
=> now show appropriate title and subtitle for format case.

docker/gondar-linux.Dockerfile, docker/mxe.Dockerfile
=> Convert tabs to 4x spaces

Makefile, infra/lint.py, infra/shared.py
=> Add 'make lint' target to gondar

.gitmodules, Makefile, docker/gondar-linux.Dockerfile, infra/lint.py
=> Enable linting on PR builder

src/chromeover_login_page.cc, src/chromeover_login_page.h, src/googleflow.cc, src/googleflow.h, src/oauth_server.cc
also remove unused func startServer
Addresses OVER-9058 and OVER-9059
in general pertains to OVER-7586
=> Handle error case for sign in with google

src/chromeover_login_page.cc
=> now set text more specifically for different errors

src/googleflow.cc
=> Allow users to reopen link after server has started

src/chromeover_login_page.cc, src/chromeover_login_page.h, src/meepo.cc, src/meepo.h
Addresses OVER-9059 by splitting signal/slots into success/fail
=> Fix previous implementation of success/fail messages

src/oauth_server.cc
=> Now redirect to meepo-controlled success/fail pages

src/chromeover_login_page.cc
=> Now properly assign site when user has just one site associated

src/write_operation_page.cc
=> Now provide more appropriate error text during USB missing case

src/error_page.cc, src/meepo.h
=> Now link users to try.neverware.com when zero sites found

src/about_dialog.cc, src/admin_check_page.cc, src/chromeover_login_page.cc, src/device.cc, src/device_picker.cc, src/device_select_page.h, src/dismissprompt.cc, src/download_progress_page.cc, src/error_page.cc, src/gondar.cc, src/gondarsite.cc, src/gondarwizard.h, src/image_select_page.cc, src/log.cc, src/neverware_unzipper.cc, src/newest_image_url.cc, src/oauth_server.cc, src/site_select_page.h, src/stubs.cc, src/util.cc, src/wizard_page.cc, test/slow_test.cc, test/slow_test.h, test/test.cc, test/test.h
=> disable clang-format for windows.h

CMakeLists.txt, src/feedback_dialog.cc, src/feedback_dialog.h, src/gondarwizard.cc, src/gondarwizard.h, src/metric.cc
Initial feedback functionality for gondar.  User will supply site if they have progressed far enough into the wizard to have a site associated.  This version uses local debug port as the server; this will be updated in a subsequent PR once the server-side changes are complete.
Addresses OVER-9424
=> Gondar feedback: OVER-9424

src/meepo.cc, src/meepo.h, src/site_select_page.cc, src/site_select_page.h
=> Now paginate site results for users with a great many sites: OVER-11068

test/test.cc
the only problem is sometimes the version changes
=> now use the actual version in test so it can pass on release branches

codebuild/master.yml, codebuild/masterchromeover.yml
=> master builds now enables metrics like release builds do: OVER-11774
