- CMakeLists.txt
- infra/gondar.cmake
It was originally separate so that different compilation flags could
be set on the old `gondar.c`, but that's no longer needed.
This should fix the linker error in https://github.com/neverware/gondar/pull/199
> Move gondar.cc into the main app library build target

- src/gondarwizard.cc
This allows the correct text to be displayed in both the original flow and the 'make another' flow.
addresses OVER-5214
I'm testing this now but looks like it ought to do the trick according to http://doc.qt.io/qt-4.8/qwizardpage.html#initializePage
> move title/subtitle setup into initializepage

- src/gondarwizard.cc
- src/gondarwizard.h
We were effectively using it as a singleshot timer anyways.
> Remove dynamically-allocated QTimer

- src/gondarwizard.cc
- src/gondarwizard.h
The `gondarwizard.h` header currently includes most of the other
headers in gondar, and is itself included in many places. This means
that a lot of recompilation is required for many trivial changes, and
compilation units are bigger than they need to be. Memory usage gets
pretty high when compiling with optimization enabled, which was
causing OOM failures on the Jenkins builder. We increased the size of
the builder, but hopefully we can also make compilation less memory
hungry by reducing the size of compilation units.
This commit adds a `Private` nested class to `GondarWizard` to contain
members that don't need to be accessed outside of `GondarWizard`. As
we improve the shared-state API we can move the rest of the pages into
that `Private` class, which should leave the `gondarwizard.h` …
> Move some GondarWizard members out of the public header

- src/chromeover_login_page.cc
- src/chromeover_login_page.h
- src/gondarwizard.cc
- src/gondarwizard.h
- src/site_select_page.cc
Moved the sites list out of the login page and up to GondarWizard so
that it can be shared with the SiteSelectPage.
> Move ChromeoverLoginPage into GondarWizard::Private

- src/download_progress_page.cc
- src/downloader.cc
- src/gondarwizard.cc
- src/usb_insert_page.cc
- src/write_operation_page.cc
Replaces SIGNAL() and SLOT() macros with member function
pointers. This helps by surfacing some errors at compile time instead
of runtime.
> Use C++11-style Qt connections

- src/downloader.cc
- src/log.cc
- src/log.h
- src/newest_image_url.cc
This allows logging of a `QUrl` without calling `toString()`.
> logging: specialize QUrl for easier logging

- src/chromeover_login_page.cc
- src/gondarimage.h
- src/gondarsite.cc
- src/gondarsite.h
- src/image_select_page.cc
- src/image_select_page.h
- src/meepo.cc
- src/site_select_page.cc
Addresses OVER-5337
Distributable images are excluded.  Previous behavior worked well for CloudReady sites, but would not display other products, and would crash if a customer only had VDI or 365 products available.
> Chromeover flow now shows build from all products

- src/about_dialog.cc
This relates to Kendall's work on better integration tests. They are
failing with an exception that didn't give enough information. They
will still fail with this fix, but with a better error message.
> about dialog: use readUtf8File

- requirements.txt
* No idea why pip-freeze gave me a 0.0.0 version, but after removing it I
was able to build environments on both machines and import everything.
> Swizzard doesn't like 0.0.0 versions

- src/gpt_pal.cc
- src/util.cc
My current solution involves chopper plopperin' the constructor I would like to use, as even though the method I want to override is virtual, calls to it from the parent constructor do not call my child method.
> Kendall 1.9 hotfix 01

- src/device_select_page.cc
- src/device_select_page.h
- src/gondarwizard.cc
- src/gondarwizard.h
- test/slow_test.cc
Changed `std::shared_ptr` to `std::unique_ptr`, removed some duplicate
constructors.
> Minor code cleanup for slowtest

- src/gondarwizard.cc
There are a number of ways to change the default size in Qt (http://doc.qt.io/qt-4.8/qwidget.html#sizePolicy-prop for example).  This is one way.  I haven't tested on windows yet, but on my machine 640 by 400 is enough size, so 640 by 480 is likely enough on windows.
> change default size to ensure text on final page is legible

- src/metric.cc
Addresses OVER-5619
I've tested this out to make sure metrics propagate for both beerover/chromeover cases correctly.  Note that there remains duplication with the 'beerover-use' and 'chromeover-use' metrics.  That is so we can continue to track the older-style version metrics over time.
> Each metric now specifies beerover or chromeover

- src/dismissprompt.cc
- src/main.cc
it appears that gcc lacks the LCIDToLocaleName func from winapi that i seem to need for this approach
See http://doc.qt.io/qt-5/qlocale.html#uiLanguages
Addresses OVER-7422
> Look up appropriate localization using Qt

- src/usb_insert_page.cc
In a meatspace discussion, @smithforrestr and I both agreed large drives should be fine.  People seem to find this warning perplexing https://www.reddit.com/r/cloudready/comments/aauwxx/putting_cloudready_on_32gb_flash_drive/
> remove large drive warning

- src/gondarwizard.cc
This produces padding for the wizard's pixmap
Addresses OVER-9895
I'll have to double-check on Windows tomorrow but on Linux this resolves the issue.
> Use classic style instead of modern

- src/admin_check_page.cc
- src/admin_check_page.h
- src/gondarimage.h
- src/gondarwizard.cc
- src/gondarwizard.h
- src/image_select_page.cc
- src/image_select_page.h
- src/newest_image_url.cc
- src/newest_image_url.h
Refactors newestImage to belong to the wizard as a whole rather than an individual page now that beerover users are skipping image selection page in its entirety.
Addresses OVER-11238
> Beerover Gondar should no longer supply 32-bit images: Addresses OVER-11238

- src/admin_check_page.cc
- src/chromeover_login_page.cc
- src/chromeover_login_page.h
- src/download_progress_page.cc
- src/downloader.cc
- src/downloader.h
- src/feedback_dialog.cc
- src/feedback_dialog.h
- src/gondarwizard.cc
- src/gondarwizard.h
- src/main.cc
- src/meepo.cc
- src/meepo.h
- src/metric.cc
- src/metric.h
- src/site_select_page.cc
- src/write_operation_page.cc
- test/test.cc
- test/test.h
Note that this PR includes a rework to move some newly-shared functionality up to the wizard-level out of individual pages.
Currently the "description" field includes version and value fields, as meepo appears to be able to infer everything else from the token such as site.
Addresses OVER-8821
> Now send metrics to meepo as well when we have a valid session token: OVER-8821

- src/newest_image_url.cc
this changes out the domain from the raw cloudfront domain to the neverware.com cname.
> changed download base url
